image: python:3.8

stages:
  - build
  - test
  - deploy

build-wheel:
  stage: build
  tags:
    - docker
  before_script:
    - echo
  script:
    - make
  artifacts:
    paths:
      - "dist/*.whl"
    expire_in: 1 week
  only:
    - tags

deploy-wheel:
  stage: deploy
  tags:
    - docker
  script:
    - python setup.py sdist
    - cp -r dist/* /opt/bretina/bin
  needs: [build-wheel]
  dependencies:
    - build-wheel
  only:
    - tags

build-docs:
  stage: build
  tags:
    - docker
  script:
    - apt update
    - apt install -y libgl1-mesa-glx
    - pip install -r requirements.txt
    - pip install -U sphinx
    - pip install sphinx-theme
    - cd docs
    - make singlehtml
  artifacts:
    paths:
      - "docs/_build/singlehtml/*"
    expire_in: 1 week
  only:
    - tags

pages:
  stage: deploy
  when: always
  image: alpine
  script:
    - mv docs/_build/singlehtml public
  artifacts:
    paths:
      - public
  needs: [build-docs]
  dependencies:
    - build-docs
  only:
    - tags
